---
- name: homebrew の tap リポジトリを追加
  homebrew_tap: tap={{ item }} state=present
  with_items: homebrew_taps

- name: homebrew をアップデート
  homebrew: update_homebrew=yes

- name: brew パッケージをインストール
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items: homebrew_packages
  register: brew_result

- name: opensslをインストール
  homebrew: >
    name=openssl
    state=linked
    install_options=force
  changed_when: false

- name: check zsh
  command: echo $SHELL
  register: shell
  changed_when: false
  tags: shell

- name: 生成されたフォントファイルをコピー
  shell: cp -f $(brew --cellar ricty)/*/share/fonts/Ricty*.ttf ~/Library/Fonts/
  args:
    creates: ~/Library/Fonts/Ricty-Bold.ttf
  notify: run fc-cache

- name: rubyのインストール
  shell: >
    eval "$(rbenv init -)";
    rbenv install {{ rbenv_ruby_version }}
    creates=~/.rbenv/versions/{{ rbenv_ruby_version }}

- shell: >
    eval "$(rbenv init -)";
    rbenv global
  register: rbenv_global_version
  changed_when: false

- name: globalに指定
  shell: >
    eval "$(rbenv init -)";
    rbenv global {{ rbenv_ruby_version }}
  when: rbenv_global_version.stdout != rbenv_ruby_version

- name: gemのインストール
  gem: name={{ item }} state=latest user_install=no executable=~/.rbenv/shims/gem
  notify: rbenv rehash
  with_items: rbenv_global_gems
